#%RAML 1.0 NamedExample
value: 
-
  ID: 1
  firstName: Bobby
  lastName: Bones
  address: Hollywood Ave
  postal: 5FAM0
  country: USA
  miles: 1500
  creationDate: 2016-02-28T16:41:41.090Z
  type: business